# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: rustup nightly
      run: |
        rustup default nightly-2022-10-15
        rustup target add wasm32-wasi

    - name: npm install, build, and test
      run: |
        chrome --version
        export CHROMIUM_BIN=$(which chrome)
        if [ $(npm --version | grep -Eo [0-9]+ | head -n 1) -lt 8 ]; then npm install npm@8 -g; fi
        npm install
        npm run build --if-present
        npm run coverage

    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
